#!/usr/bin/bash

# Stop on error
set -e

# Remove venv
rm -rf test_venv

BRANCH=$(git branch --show-current)

# Add venv
python -m venv test_venv
. ./test_venv/bin/activate

# Upgrade pip
python -m pip install --upgrade pip

# Install the library
pip install git+https://github.com/IliTheButterfly/EasyBuilderMacroGenerator.git@$BRANCH


# Run code to test
python ./examples/simple.py