from eb_macro_gen.syntax import *
from eb_macro_gen.objects import *

def main():
    # Give a name and a description to your macro
    macro1 = Macro("test_macro1", "A test macro")
    
    # You should define the name of the HMI and PLS(s) globally for ease of use
    
    HMI_NAME = "Local HMI"
    PLC_NAME = "My PLC"
    
    # You can have global variables or tags, they will only appear in the final macro if
    # they are actually used
    
    # You can use tags by their address
    tag1 = Tag("tag1", HMI_NAME, "LB,1", DataType.Bit)
    # Or by their address name
    tag2 = Tag("tag2", HMI_NAME, string_literal("tag2"), DataType.S16)
    tag3 = Tag("tag3", HMI_NAME, string_literal("tag3"), DataType.U32)
    tag4 = Tag("tag4", HMI_NAME, string_literal("tag4"), DataType.F32)
    
    # Note the use of 'string_literal'. It is needed to differenciate between 
    # addresses and address names. It essentially adds '"' at the beginning and end
    
    # It is generally preferable to use tag names as they will still correspond 
    # if you change their addresses
    
    # As mentioned, you can have global variables
    tag1_value = vbool("tag1_value", False) # You can add a default value
    tag2_value = vshort("tag2_value") # Or not
    tag3_value = vuint("tag3_value")
    tag4_value = vfloat("tag4_value")
    
    # This silently calls begin() and end() (on exit) to setup the pre and post statements
    # required for the macro
    with macro1:
        # You can define tags and variables anywhere, but this makes it more verbose
        my_bool = vbool("my_bool", True)
        
        
        # Now for the fun part
        macro1.write(
            # You can write your code here
            
            # You can make comments
            COMMENT("Start of the macro"),
            
            # Empty lines
            EMPTY(),
            
            # Read or write tags
            tag1.read(tag1_value),
            tag2.read(tag2_value),
            
            IF(tag1_value & tag2_value > 10)( # If statements with expressions
                # Body of the if statement
                
                # Assignments
                tag3_value.set(tag2_value + 1),
            ).ELIF(~tag1_value)( # Else if statements
                # Body of else if statement
                my_bool.set(False),
            ).ELSE()( # Else statements
                # Body of the else statement
                tag4_value.set(30),
            ),
            
            # Blocks
            BLOCK(
                # The use of blocks will be discussed in the next macro
                
                # The std instructions can also be called directly
                GetData(tag4_value, HMI_NAME, string_literal("tag4")),
                tag4.read(tag4_value),
                # These last two statements are actually equivalent
                # The use of tags is recommended because it makes it cleaner
            ),
            
        )
        
        
    macro1.display()
    """
// GENERATED CODE
// This code was generated by a script.
// See https://github.com/IliTheButterfly/EasyBuilderMacroGenerator


// A test macro
macro_command main()
    float tag4_value
    short tag2_value
    unsigned int tag3_value
    bool tag1_value = 0
    bool my_bool = 1
    
    // Start of the macro
    
    GetData(tag1_value, "Local HMI", LB,1, 1)
    GetData(tag2_value, "Local HMI", "tag2", 1)
    if (tag1_value and tag2_value) > 10 then
        tag3_value = tag2_value + 1
    else if (not tag1_value) then
        my_bool = False
    else
        tag4_value = 30
    end if
    GetData(tag4_value, "Local HMI", "tag4", 1)
    GetData(tag4_value, "Local HMI", "tag4", 1)
end macro_command
    """
    
    macro2 = Macro("test_macro2", "A more complex use of a macro")
    
    with macro2:
        # What we've seen so far doesn't seem like it adds anything
        # to the original programming language. Here is a more common use
        # of this library where it can truly shine
        
        # Let's say we have some tags on the PLC that all represent an instance
        # of the same object. For example, a valve. We want one screen to control
        # any of those valves. On the screen, you can see those valves and when clicked,
        # they get selected to be controlled
        
        # This is a simplified implementation. This typically requires 3 or 4 macros:
        # - One to read the values once a valve is selected
        # - One to update the values in real time while a valve is selected
        # - One to write the values once an action on the HMI is executed
        # - One to reset the selection tags to prevent more than one selected valve
        
        # This example only covers the writing macro
        
        # Valve names
        VALVE_NAMES = ["V200", "V201", "V300", "V400", "V401", "V402"]
        
        # Those valves can be opened or closed but we want to control them with the same button
        valve_cmd_ind = Tag("valve_cmd_ind", HMI_NAME, string_literal("valve_cmd_ind"), DataType.Bit)
        
        selected = vbool("selected") # Variable to store if valve is selected
        valve_cmd_value = vbool("valve_cmd_value")
        
        
        for valve_name in VALVE_NAMES:
            # This is the actual PLC tag
            valve_cmd = Tag(f"{valve_name}_cmd", PLC_NAME, string_literal(f"{valve_name}_cmd"), DataType.Bit)
            
            # These tags get set when clicking on the valves themselves
            selection = Tag(valve_name, HMI_NAME, string_literal(valve_name), DataType.Bit)
            
            # Time to write the code for this valve
            macro2.write(
                COMMENT(f"{valve_name} selected"),
                EMPTY(),
                COMMENT("Read selection"),
                selection.read(selected),
                IF(selected)(
                    COMMENT("Read command from HMI"),
                    valve_cmd_ind.read(valve_cmd_value),
                    COMMENT("Write command to PLC"),
                    valve_cmd.write(valve_cmd_ind),
                ),
                EMPTY(),
            )
    macro2.display()
    """
// GENERATED CODE
// This code was generated by a script.
// See https://github.com/IliTheButterfly/EasyBuilderMacroGenerator


// A more complex use of a macro
macro_command main()
    bool valve_cmd_value
    bool selected
    
    // V200 selected
    
    // Read selection
    GetData(selected, "Local HMI", "V200", 1)
    if selected then
        // Read command from HMI
        GetData(valve_cmd_value, "Local HMI", "valve_cmd_ind", 1)
        // Write command to PLC
        SetData(<eb_macro_gen.objects.Tag object at 0x7f0588e94b00>, "My PLC", "V200_cmd", 1)
    end if
    
    // V201 selected
    
    // Read selection
    GetData(selected, "Local HMI", "V201", 1)
    if selected then
        // Read command from HMI
        GetData(valve_cmd_value, "Local HMI", "valve_cmd_ind", 1)
        // Write command to PLC
        SetData(<eb_macro_gen.objects.Tag object at 0x7f0588e94b00>, "My PLC", "V201_cmd", 1)
    end if
    
    // V300 selected
    
    // Read selection
    GetData(selected, "Local HMI", "V300", 1)
    if selected then
        // Read command from HMI
        GetData(valve_cmd_value, "Local HMI", "valve_cmd_ind", 1)
        // Write command to PLC
        SetData(<eb_macro_gen.objects.Tag object at 0x7f0588e94b00>, "My PLC", "V300_cmd", 1)
    end if
    
    // V400 selected
    
    // Read selection
    GetData(selected, "Local HMI", "V400", 1)
    if selected then
        // Read command from HMI
        GetData(valve_cmd_value, "Local HMI", "valve_cmd_ind", 1)
        // Write command to PLC
        SetData(<eb_macro_gen.objects.Tag object at 0x7f0588e94b00>, "My PLC", "V400_cmd", 1)
    end if
    
    // V401 selected
    
    // Read selection
    GetData(selected, "Local HMI", "V401", 1)
    if selected then
        // Read command from HMI
        GetData(valve_cmd_value, "Local HMI", "valve_cmd_ind", 1)
        // Write command to PLC
        SetData(<eb_macro_gen.objects.Tag object at 0x7f0588e94b00>, "My PLC", "V401_cmd", 1)
    end if
    
    // V402 selected
    
    // Read selection
    GetData(selected, "Local HMI", "V402", 1)
    if selected then
        // Read command from HMI
        GetData(valve_cmd_value, "Local HMI", "valve_cmd_ind", 1)
        // Write command to PLC
        SetData(<eb_macro_gen.objects.Tag object at 0x7f0588e94b00>, "My PLC", "V402_cmd", 1)
    end if
    
end macro_command
    """
    
    # By this point, it should be obvious how this library can be a big time save
            
    macro3 = Macro("test_macro3", "A use case for blocks")
    
    with macro3:
        # It's time to learn about blocks. They might seem redundant and useless,
        # but they have a specific use
        
        # In a similar case to macro2, we want to read/write multiple tags. Unfortunately,
        # EasyBuilder Pro macros don't allow the use of a string as a tag name for the 
        # GetData/SetData/etc instructions. The string needs to be a literal.
        # For that reason, python for loops can be used to essentially copy-paste
        # pieces of code with their appropriate variations. Blocks help inline these
        # variations
        
        TANK_NAMES = ["T01", "T02", "T03"]
        BIT_VALUES = ["v1", "v2", "v3", "v4"]
        WORD_VALUES = ["w1", "w2", "w3", "w4"]
        
        selected = vbool("selected")
        bit_value = vbool("bit_value")
        word_value = vshort("word_value")
        
        bit_tags_ind = {name : Tag(f"{name}_ind", HMI_NAME, string_literal(f"{name}_ind"), DataType.Bit) for name in BIT_VALUES}
        word_tags_ind = {name : Tag(f"{name}_ind", HMI_NAME, string_literal(f"{name}_ind"), DataType.S16) for name in WORD_VALUES}
        
        for tank in TANK_NAMES:
            selection = Tag(tank, HMI_NAME, string_literal(tank), DataType.Bit)
            
            macro3.write(
                COMMENT(tank),
                selection.read(selected),
                IF(selected)(
                    COMMENT("Read bits"),
                    *[
                        BLOCK(
                            Tag(f"{tank}_{name}", PLC_NAME, string_literal(f"{tank}_{name}"), DataType.Bit).read(bit_value),
                            bit_tags_ind[name].write(bit_value),
                        )
                        for name in BIT_VALUES
                    ],
                    COMMENT("Read words"),
                    *[
                        BLOCK(
                            Tag(f"{tank}_{name}", PLC_NAME, string_literal(f"{tank}_{name}"), DataType.S16).read(word_value),
                            word_tags_ind[name].write(word_value),
                        )
                        for name in WORD_VALUES
                    ]
                )
            )
        
    macro3.display()
    """
// GENERATED CODE
// This code was generated by a script.
// See https://github.com/IliTheButterfly/EasyBuilderMacroGenerator


// A use case for blocks
macro_command main()
    bool selected
    bool bit_value
    short word_value
    
    // T01
    GetData(selected, "Local HMI", "T01", 1)
    if selected then
        // Read bits
        GetData(bit_value, "My PLC", "T01_v1", 1)
        SetData(bit_value, "Local HMI", "v1_ind", 1)
        GetData(bit_value, "My PLC", "T01_v2", 1)
        SetData(bit_value, "Local HMI", "v2_ind", 1)
        GetData(bit_value, "My PLC", "T01_v3", 1)
        SetData(bit_value, "Local HMI", "v3_ind", 1)
        GetData(bit_value, "My PLC", "T01_v4", 1)
        SetData(bit_value, "Local HMI", "v4_ind", 1)
        // Read words
        GetData(word_value, "My PLC", "T01_w1", 1)
        SetData(word_value, "Local HMI", "w1_ind", 1)
        GetData(word_value, "My PLC", "T01_w2", 1)
        SetData(word_value, "Local HMI", "w2_ind", 1)
        GetData(word_value, "My PLC", "T01_w3", 1)
        SetData(word_value, "Local HMI", "w3_ind", 1)
        GetData(word_value, "My PLC", "T01_w4", 1)
        SetData(word_value, "Local HMI", "w4_ind", 1)
    end if
    // T02
    GetData(selected, "Local HMI", "T02", 1)
    if selected then
        // Read bits
        GetData(bit_value, "My PLC", "T02_v1", 1)
        SetData(bit_value, "Local HMI", "v1_ind", 1)
        GetData(bit_value, "My PLC", "T02_v2", 1)
        SetData(bit_value, "Local HMI", "v2_ind", 1)
        GetData(bit_value, "My PLC", "T02_v3", 1)
        SetData(bit_value, "Local HMI", "v3_ind", 1)
        GetData(bit_value, "My PLC", "T02_v4", 1)
        SetData(bit_value, "Local HMI", "v4_ind", 1)
        // Read words
        GetData(word_value, "My PLC", "T02_w1", 1)
        SetData(word_value, "Local HMI", "w1_ind", 1)
        GetData(word_value, "My PLC", "T02_w2", 1)
        SetData(word_value, "Local HMI", "w2_ind", 1)
        GetData(word_value, "My PLC", "T02_w3", 1)
        SetData(word_value, "Local HMI", "w3_ind", 1)
        GetData(word_value, "My PLC", "T02_w4", 1)
        SetData(word_value, "Local HMI", "w4_ind", 1)
    end if
    // T03
    GetData(selected, "Local HMI", "T03", 1)
    if selected then
        // Read bits
        GetData(bit_value, "My PLC", "T03_v1", 1)
        SetData(bit_value, "Local HMI", "v1_ind", 1)
        GetData(bit_value, "My PLC", "T03_v2", 1)
        SetData(bit_value, "Local HMI", "v2_ind", 1)
        GetData(bit_value, "My PLC", "T03_v3", 1)
        SetData(bit_value, "Local HMI", "v3_ind", 1)
        GetData(bit_value, "My PLC", "T03_v4", 1)
        SetData(bit_value, "Local HMI", "v4_ind", 1)
        // Read words
        GetData(word_value, "My PLC", "T03_w1", 1)
        SetData(word_value, "Local HMI", "w1_ind", 1)
        GetData(word_value, "My PLC", "T03_w2", 1)
        SetData(word_value, "Local HMI", "w2_ind", 1)
        GetData(word_value, "My PLC", "T03_w3", 1)
        SetData(word_value, "Local HMI", "w3_ind", 1)
        GetData(word_value, "My PLC", "T03_w4", 1)
        SetData(word_value, "Local HMI", "w4_ind", 1)
    end if
end macro_command
    """
            
        
    
if __name__ == "__main__":
    main()