"""eb_macro_gen — generate EasyBuilder Pro macros from Python.

The most commonly used names are re-exported here for convenience:

    from eb_macro_gen import Macro, IF, vint, COMMENT

Submodules (``syntax``, ``objects``, ``instructions``, ``dynamic_drawing``,
``common``, ``tools``) remain importable directly for advanced use.
"""

from .common import DoubleKeyMap, PromptResult, prompt_yna, smart_split
from .syntax import (
    AND,
    ASSIGNMENT,
    BEGIN_MACRO,
    BLOCK,
    BREAK,
    CALL,
    CASE,
    COMMENT,
    CONTINUE,
    C_ELIF,
    C_ELSE,
    C_END_IF,
    C_IF,
    C_MAX,
    C_MIN,
    EMPTY,
    END_MACRO,
    EVAL,
    EXPRESSION,
    IF,
    LITERAL,
    NOT,
    OR,
    RETURN,
    STATEMENT,
    SWITCH,
    Macro,
    Resource,
    Variable,
    VariableArray,
    VariableItem,
    deboolify,
    vbool,
    vbool_arr,
    vchar,
    vchar_arr,
    vdouble,
    vdouble_arr,
    vfloat,
    vfloat_arr,
    vint,
    vint_arr,
    vlong,
    vlong_arr,
    vshort,
    vshort_arr,
    vuchar,
    vuchar_arr,
    vuint,
    vuint_arr,
    vulong,
    vulong_arr,
    vushort,
    vushort_arr,
)
from .objects import (
    DT_EB_MAP,
    EB_DT_MAP,
    DataType,
    EasyBuilderTag,
    EasyBuilderTagList,
    ROUTINE,
    Tag,
    TagList,
    is_float,
    is_int,
)

__version__ = "1.1.1"

__all__ = [
    "__version__",
    # common
    "DoubleKeyMap",
    "PromptResult",
    "prompt_yna",
    "smart_split",
    # syntax — flow control
    "IF",
    "C_IF",
    "C_ELIF",
    "C_ELSE",
    "C_END_IF",
    "SWITCH",
    "CASE",
    "BREAK",
    "CONTINUE",
    "RETURN",
    "CALL",
    # syntax — building blocks
    "Macro",
    "BLOCK",
    "BEGIN_MACRO",
    "END_MACRO",
    "STATEMENT",
    "EMPTY",
    "COMMENT",
    "ASSIGNMENT",
    "Resource",
    # syntax — expressions
    "EVAL",
    "EXPRESSION",
    "LITERAL",
    "AND",
    "OR",
    "NOT",
    "C_MIN",
    "C_MAX",
    # syntax — variables
    "Variable",
    "VariableArray",
    "VariableItem",
    "deboolify",
    "vbool",
    "vbool_arr",
    "vchar",
    "vchar_arr",
    "vdouble",
    "vdouble_arr",
    "vfloat",
    "vfloat_arr",
    "vint",
    "vint_arr",
    "vlong",
    "vlong_arr",
    "vshort",
    "vshort_arr",
    "vuchar",
    "vuchar_arr",
    "vuint",
    "vuint_arr",
    "vulong",
    "vulong_arr",
    "vushort",
    "vushort_arr",
    # objects
    "DataType",
    "DT_EB_MAP",
    "EB_DT_MAP",
    "EasyBuilderTag",
    "EasyBuilderTagList",
    "ROUTINE",
    "Tag",
    "TagList",
    "is_float",
    "is_int",
]
