import sqlite3
import argparse
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser("recipe_import")
    parser.add_argument("db_file", help="The exported recipe db file")
    parser.add_argument("out_file", help="The generated python file")
    parser.add_argument("-f", "--force", action="store_true")

    args = parser.parse_args(sys.argv[1:])

    db_file = Path(args.db_file)
    out_file = Path(args.out_file)

    if not db_file.exists():
        parser.error(f"db_file '{db_file}' does not exist")

    with sqlite3.connect(str(db_file)) as db:
        cursor = db.cursor()

        # List all tables in the recipe database
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        tables = [row[0] for row in cursor.fetchall()]

        if not tables:
            print("No tables found in database.")
            return

        lines = [
            "# Auto-generated by recipe_import",
            "# Recipe database: " + str(db_file),
            "",
        ]

        for table in tables:
            cursor.execute(f"SELECT * FROM \"{table}\";")
            rows = cursor.fetchall()
            col_names = [desc[0] for desc in cursor.description]

            lines.append(f"# Table: {table}")
            lines.append(f"{table}_columns = {col_names!r}")
            lines.append(f"{table}_rows = [")
            for row in rows:
                lines.append(f"    {list(row)!r},")
            lines.append("]")
            lines.append("")

        output = "\n".join(lines)

        if out_file.exists() and not args.force:
            print(f"Output file '{out_file}' already exists. Use -f to overwrite.")
            sys.exit(1)

        out_file.write_text(output)
        print(f"Written to {out_file}")


if __name__ == "__main__":
    main()